// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HrBackend.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string EmployeeId { get; set; }

    public string FullName { get; set; }

    public string EnglishName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string Role { get; set; }

    public bool IsActive { get; set; }

    public string Department { get; set; }

    public string Position { get; set; }

    public DateOnly? OnboardDate { get; set; }

    public DateOnly? LeaveDate { get; set; }

    public string Phone { get; set; }

    public string EmergencyContact { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}